### PR TITLE
Change: (solaire-mode-reset) Set mode appropriately in all buffers

### PR DESCRIPTION
**Pull request by alphapapa**
This seems more correct and useful.

### CODE REVIEW

**Comment by hlissner** [comment]
I'm afraid I cannot accept this PR. This breaks the intended purpose of the function. `turn-on-solaire-mode` enables solaire-mode _conditionally_, but it is entirely possible for solaire-mode to be activated _unconditionally_ by the user in a buffer that wouldn't normally meet the criteria. For example, if it were enabled via hook: `(add-hook 'ediff-prepare-buffer-hook #'solaire-mode)`.

In this case, since ediff buffers are considered "unreal", `solaire-mode-reset` would disable solaire-mode in them, instead of cycling it unconditionally.

**Comment by alphapapa** [comment]
I guess I don't understand the purpose of `solaire-mode-reset` then.  `solaire-mode` is a buffer-local variable, so `solaire-mode-reset` simply turns `solaire-mode` off and on again in buffers that already have it enabled.  What's the purpose of doing that when it's already enabled?

The function in this PR is useful for e.g. calling in `window-configuration-change-hook`.  For example, I wanted `solaire-mode` enabled in "side windows," like `org-now`'s side window.  But when the `org-now` buffer is first created, it's not visible in a window, so the globalized minor mode would never enable it.  By adding this PR's function to `window-configuration-change-hook`, the buffer would have the mode activated appropriately after being shown in a window.

I think another confusing issue is the name of `turn-on-solaire-mode`.  The name implies that it turns the mode on, but actually the function only *might* turn on the mode.  I think it would be helpful if it were named differently, something like `solaire-mode-maybe-enable`, which would imply that it does a check and only enables the mode when appropriate.

**Comment by hlissner** [comment]
> I guess I don't understand the purpose of solaire-mode-reset then. solaire-mode is a buffer-local variable, so solaire-mode-reset simply turns solaire-mode off and on again in buffers that already have it enabled. What's the purpose of doing that when it's already enabled?

The reset function serves two purposes:

1. To reset the fringe's background color. Unlike other faces, the fringe cannot be buffer-local, so we have to modify it globally. There are events that cause the fringe to revert to its defaults like loading a new theme or opening an Emacs client frame with a different display (via emacsclient), etc.

2. To reorder the `face-remapping-alist` variable, to correct the rare case where other remappings have stolen precedence.

> The function in this PR is useful for e.g. calling in window-configuration-change-hook

The old `solaire-mode-reset` wouldn't work for this purpose? Your PR hasn't modified it in any way that would change its compatibility with `window-configuration-change-hook`, as far as I can tell.

> But when the org-now buffer is first created, it's not visible in a window, so the globalized minor mode would never enable it.

I don't understand this. The window not being visible should not affect solaire-mode. If `(solaire-mode--real-buffer-p)` returns `t` in the buffer we're talking about, it should be activated there, regardless of its visibility.

Perhaps that's the functionality you want? e.g.

```elisp
(setq solaire-mode-real-buffer-fn
      (lambda (buf) (or (solaire-mode--real-buffer-p)
                        (eq (window-dedicated-p) 'side))))
```

By default, solaire-mode determines whether a buffer is "real" only by checking if it is file-visiting (i.e. if `buffer-file-name` has a local value). If you wanted it enabled in other buffers, you either need to change the predicate in `solaire-mode-real-buffer-fn` or manually, with hooks: `(add-hook 'some-mode-hook #'solaire-mode)`.

> I think another confusing issue is the name of turn-on-solaire-mode. The name implies that it turns the mode on, but actually the function only might turn on the mode. I think it would be helpful if it were named differently, something like solaire-mode-maybe-enable, which would imply that it does a check and only enables the mode when appropriate.

While I agree with you, the `turn-on-X` name is an Emacs convention for conditional activators of globalized minor modes. I was aiming for consistency with those. That said, the docstring could be clearer.

**Comment by alphapapa** [comment]
> To reset the fringe's background color. Unlike other faces, the fringe cannot be buffer-local, so we have to modify it globally. There are events that cause the fringe to revert to its defaults like loading a new theme or opening an Emacs client frame with a different display (via emacsclient), etc.

Ah, I see.  It would be helpful if that were mentioned in the docstring or in a source comment.  :)

> To reorder the face-remapping-alist variable, to correct the rare case where other remappings have stolen precedence.

I wonder if that might be part of the problem or solution regarding #15...

> The old solaire-mode-reset wouldn't work for this purpose? Your PR hasn't modified it in any way that would change its compatibility with window-configuration-change-hook, as far as I can tell.

> Perhaps that's the functionality you want? e.g.
> 
```
(setq solaire-mode-real-buffer-fn
     (lambda (buf) (or (solaire-mode--real-buffer-p)
                         (eq (window-dedicated-p) 'side))))
```
> 
> By default, solaire-mode determines whether a buffer is "real" only by checking if it is file-visiting (i.e. if buffer-file-name has a local value). If you wanted it enabled in other buffers, you either need to change the predicate in solaire-mode-real-buffer-fn or manually, with hooks: (add-hook 'some-mode-hook #'solaire-mode).

Yes, I neglected to mention that I was using a custom `solaire-mode-real-buffer-fn`.

> While I agree with you, the turn-on-X name is an Emacs convention for conditional activators of globalized minor modes. I was aiming for consistency with those. That said, the docstring could be clearer.

I see, well, consistency is good.  :)  Maybe it could also have an `solaire-mode-maybe-enable` alias.

Now that we're on the same page, I'd be happy to change the function's name if you think it would be useful to have.  If not, I'll keep it in my own config.

Thanks for your work.

**Comment by hlissner** [comment]
Sorry for a tremendously late follow up. I've updated the docstrings for both `solaire-mode-reset` and `turn-on-solaire-mode` to include what we've discussed. I'm going to stick to `turn-on-solaire-mode` just because it's the most widely used convention (a smattering of plugins use `X-mode-maybe`, flycheck uses `flycheck-mode-on-safe`, magit uses `magit-file-mode-turn-on`, etc), so I'll consider any variation on that to be personal preference.

In any case, I'll consider this thread resolved. Thanks for bringing it to my attention!

**Pull request closed without merging**
